### ISSUE TITLE
Read and write from google drive

### ISSUE THREAD

**Issue by dkbast** [glenreesor/m3#1]
Hey - I really love your project. Would you be interested in building google drive support into it? It would be amazing to have real mindmaps in the cloud :)

**Comment by glenreesor** [comment]
Glad you like it! It hasn't been updated in a while due to other personal projects, however my plan is to evolve the code base so it can be used to create a cross platform application (Windows, Linux, MacOS, Android, iOS) -- in addition to the current web-based one. And while doing that, I intend to include syncing w/Google drive and dropbox.
