### ISSUE TITLE
Design & UI/X Planning

### ISSUE THREAD

**Issue by mattsbennett** [glenreesor/m3#2]
Hey @glenreesor!

I've had a look at the repository and the existing features/UX (this is cool!), and came up with:

1. A desktop landing page concept (I had this around from previous discussions, but haven't got to creating a mobile version).
2. A preliminary mobile UX flow (not fully fleshed out). My primary goal here was to capture all the existing functionality and behaviour into a flow that would be something acheivable for an initial UI/X MVP without requiring any major changes to the existing functionality). I had some ideas for future functionality as I went through this (and I'm sure you have more!), but I was thinking it might make sense to focus on implementing the initial UI/X before thinking/planning any further there?

Anyhow, let me know your thoughts!

[m3landingpagedesktop.pdf](https://github.com/glenreesor/m3/files/7875600/m3landingpagedesktop.pdf) (edit: updated)
[m3mobileflow.pdf](https://github.com/glenreesor/m3/files/7874567/m3mobileflow.pdf)

(Also, I'm not sure if issues are the best place for this kind of discussion, so feel free to remove/direct this elsewhere 😄)

**Comment by glenreesor** [comment]
Hey @mattsbennett this is awesome! Love those ideas, as well as the thought to address the current functionality in your mocks. In terms of an MVP, I'm thinking along the lines of prioritizing functionality that I use myself (I've been dog-fooding this for a few weeks now using Android Chrome and having the m3 files on the local Android filesystem).

For reference, here are some of the things I'd like to address in the near future:
- add a button that shows "About" info (copyright, authors, credits for third party SVGs etc)
- copy/paste (I'm really noticing this absence in my dog-fooding :-) )
- Android app -- nothing fancy, just wrap the existing functionality in Cordova so dog-fooders aren't at the mercy of an accidental browser cache clear
- Desktop app -- again, nothing fancy UX wise, just have the ability to edit things on a desktop since that would be super helpful for me :-). There's Electron, but also https://tauri.studio/en/ , which looks promising
- Adding tests -- in particular for the document state management and file management
- And finally, some refactoring, since I got impatient with the dog fooding and a number of things are hacks :-)

Sooooo! Perhaps we should touch base offline (so to speak) about next steps!

**Comment by glenreesor** [comment]
Forgot to mention some future ideas I have, beyond the next iteration. In no particular order:
- better wrapping logic for really long nodes
- support for multi-line nodes
- search / replace / filter
- markdown or ascii doc
- inertia scroll
- mini map
- shared editing
- syncing between desktop and mobile apps
- bookmarks
- compartmentalizing it to make it easily embeddable in other places like Wordpress and Moodle
- the ability to save a document along with the js/css/etc so you could save the doc, send the whole thing to someone via email, and they could then view the document without having to install anything
- presentation mode -- define a sequence of movements, folding, unfolding, etc so you could just click "Next" and the next movement etc would happen automatically
- and many more ....

**Comment by glenreesor** [comment]
Great start to collaboration!
